#!/usr/bin/bash

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

export TERM=xterm-256color

# Directories
export CODE_DIR=$HOME/Documents/code
export WORK_DIR=$HOME/Documents/workcode

export SWITCH_DIR=$WORK_DIR
export SWITCH_IOS_DIR=$SWITCH_DIR/ios

export FLY_VENV=$CODE_DIR/fly/venv
export FLY_APP_DIR=$CODE_DIR/fly/server

# Commands
PATH=$PATH:$CODE_DIR/fly/server/bin
PATH=$PATH:$SWITCH_IOS_DIR/bin
PATH=$PATH:$CODE_DIR/dotfiles/bin

#Alias
alias up='ping 8.8.8.8'
alias gc='git commit'
alias gca='git commit -a'
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias gb='git branch'
alias gk='git checkout'
alias gl='git log'
alias ska='echo "Killing core audio"; sudo killall coreaudiod;'
alias bump="git commit -a -m \"Bump build no\""
alias clear-derived-data='rm -rf ~/Library/Developer/Xcode/DerivedData'
alias grepr='grep -RniI'
alias record='rm ~/Downloads/appvideo.mov || xcrun simctl io booted recordVideo ~/Downloads/appvideo.mov'
alias opendl='xcrun simctl openurl booted'

function jca () {
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; then
        echo "error: Enter JIRA Ticket" >&2;
        return 1;
    elif [ -z $2 ] ; then
        echo "error: Enter a comment";
        return 1;
    else
        gca -m "[TRIP-$1] ${*:2}"
    fi
}

