#!/usr/bin/bash

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

export TERM=xterm-256color

# Directories
export CODE_DIR=$HOME/Documents/code

# Commands
PATH=$PATH:$CODE_DIR/dotfiles/bin

#Alias
alias up='ping 8.8.8.8'
alias gc='git commit'
alias gca='git commit -a'
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias gb='git branch'
alias gk='git checkout'
alias gl='git log'
alias ska='echo "Killing core audio"; sudo killall coreaudiod;'
alias bump="git commit -a -m \"Bump build no\""
alias clear-derived-data='rm -rf ~/Library/Developer/Xcode/DerivedData'
alias grepr='grep -RniI'
